### ISSUE TITLE
Ghost cards

### ISSUE THREAD

**Issue by SickNick44** [notmario/MoreFluff#69]
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/014ce561-deeb-4dc0-af0d-a02edbe59b20" />

for some reason when i destroy cards i get ghost cards that cannot be played nor discarded, but take up slots in my hand. you can see the cards i have in my deck are more than remaining cards.

**Comment by notmario** [comment]
what version do you have? this should be fixed on main

**Comment by SickNick44** [comment]
> what version do you have? this should be fixed on main

not sure what version i had but i just updated it so hopefully its fixed now

**Comment by SickNick44** [comment]
> what version do you have? this should be fixed on main

ok i played the newest version and the ghost cards are kind of fixed. they still show up but now they have 2 back sides and are selectable, and have no default rank or suit. they can also take modifications like normal cards, and can have their rank and suit modified turning them into other cards, however even after being modified they still retain the 2 back sides.

**Comment by SickNick44** [comment]
> what version do you have? this should be fixed on main

i also noticed that the faceless card is the card you use to view your deck, meaning when selecting it it shows the hud that shows your deck when you hover over it

**Comment by notmario** [comment]
oh wait i fixed the issue lol
